### ISSUE TITLE
Invalid performance data values

### ISSUE THREAD

**Issue by gino0631** [NETWAYS/check_iftraffic#3]
The performance data is not in the [expected format](https://nagios-plugins.org/doc/guidelines.html#AEN200) and therefore gets dropped, e.g.:
`warning/InfluxdbWriter: Ignoring invalid perfdata value: outUsage=0.1,85,98`

**Comment by dnsmichi** [comment]
Missing a PR, so I've added your remote and cherry-picked the commit. Thanks.
